### ISSUE TITLE
Convertion to 2018 Module System

### ISSUE THREAD

**Issue by NathanielAJohnson** [vulkano-rs/vulkano#1042]
I tried converting the Triangle example to use the [2018 Module System](https://rust-lang-nursery.github.io/edition-guide/rust-2018/module-system/index.html)  and got (surprisingly) far.  Everything imports correctly with no changes to library source until I get to the macros.  The new syntax calls for a straight `use` but I get an error that indicates the macros are private.  Hopefully this means the only src changes are to change the macros to public.

**Comment by rukai** [comment]
You should be able to create a crate that uses rust 2018 that has dependencies that do not use rust 2018. If you cant then that is a bug that should be filed at https://github.com/rust-lang/rust

**Comment by rukai** [comment]
I see, so vulkano does work with rust 2018. However if we want to allow users to leave out the `#[macro_use] extern crate vulkano;` then we need to make the macros public. I'll put together a PR.

**Comment by rukai** [comment]
You were importing your macros at the wrong path. Try this instead:
```
use vulkano::single_pass_renderpass;
use vulkano::ordered_passes_renderpass;
use vulkano::impl_vertex;
```
full triangle example: [main.rs](https://github.com/vulkano-rs/vulkano/files/2388630/main.txt)

`use vulkano_shader_derive::VulkanoShader;` does not cause an error.
However the `#[derive(VulkanoShader)]`s fail because VulkanoShader derive cant be found.
I suspect this might be because the VulkanoShader trait doesnt exist.
However I'll leave this till after I cleanup the shader macros. https://github.com/vulkano-rs/vulkano/issues/1039

**Comment by NathanielAJohnson** [comment]
Thank you @rukai .  I followed your instructions and found the same issues as you.  Macros are not my strong suite so I can't really help with PR.  Would you bump this issue with PR so I can mark it closed when done or would you like me to close now?

**Comment by rukai** [comment]
Yeah keep it open to track not being able to import VulkanoShader derive.

**Comment by rukai** [comment]
Because we are now using function-like proc macro instead of derive proc macro, this is no longer an issue. Take the triangle example https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs , add it to a 2018 crate, delete the `extern crate`s, add the appropriate `use`s. It will compile and run fine.
