### ISSUE TITLE
vulkano-shaders example errors

### ISSUE THREAD

**Issue by rokit** [vulkano-rs/vulkano#1049]
I'm getting errors about `vulkano_shaders::compile` and `vulkano_shaders::ShaderKind` not being part of `vulkano_shaders`.

**Comment by rukai** [comment]
Sorry, can I get more details? Copy and paste the full error would be nice. It sounds like your getting this error when running an example? Which one?

**Comment by rokit** [comment]
This is the example:
https://github.com/vulkano-rs/vulkano/blob/master/vulkano-shaders/examples/example.rs

Notice on line 42:
`vulkano_shaders::compile`

The error I was getting was saying `compile` was not part of `vulkano_shaders`. Same with `ShaderKind`.

**Comment by rukai** [comment]
My bad, your original post was fine, I misread "vulkano-shaders example errors" as "vulkano example errors". This will be because of rececnt changes making git master out of sync with the crates.io released version. vulkano-shaders is mostly an implementation detail of vulkano, it generates rust code to be embedded in a vulkano application. So I'm not sure what you actually want to do with it. Maybe you are after something like https://github.com/google/shaderc-rs ?

**Comment by rokit** [comment]
No worries. Yes, I was using shaderc before, but thought I might not be doing something right, so I just wanted to try vulkan_shader. I thought the example might be out of date, but I didn't know it was just a code generator. Thanks for clearing things up.
