### ISSUE TITLE
Compile error when pushing 2 or more Vector3<f32> to shader as uniform

### ISSUE THREAD

**Issue by skemps** [vulkano-rs/vulkano#1064]
Hi, I get compile error 

> missing field '_dummy0' in initializer ...
when trying to push 2 or more Vec3<f32> to shader like this:
```
let light_data = vertex_shader::ty::Light {
            pos: directional_position.into(),
            color: directional_color.into(),
        };
```
It works ok for Vector2, Vector4, Matrix4 but not for Vector3.

**Comment by rukai** [comment]
When vulkano generates the Light struct, it includes padding fields, so that the bytes match exactly what the shader expects the struct to look like.

Working code will look something like:
```
let light_data = vertex_shader::ty::Light {
            _dummy0: [0],
            pos: directional_position.into(),
            color: directional_color.into(),
        };
```

Exactly what the code should look like will depend on how big the u8 array is on the _dummy0 field.

To find exactly how to create your struct, you can expect the generated Light struct code with a tool like https://github.com/dtolnay/cargo-expand
