### ISSUE TITLE
Mention that vec3[] still needs 4 elements

### ISSUE THREAD

**Issue by jvanbruegge** [vulkano-rs/vulkano#1111]
It took me a the whole day to debug why my shader did not receive the data I was sending:
```
layout(set = 0, binding = 0) uniform SomeData {
    vec3[] numbers;
} buf;
```
Turns out that instead of using `Buffer::fromIter<Vec<[f32; 3]>` I need to use a `Vec<[f32; 4]>` and fill the last element with some garbage (ie 0).

Might be good to have this somewhere in the docs (there is no example that sends a `vecX` to the shader.

**Comment by jvanbruegge** [comment]
Now I am again stuck with memory layout on the shader side. I am super happy with vulkano, but a section in the guide would so helpful.

**Comment by knappador** [comment]
@jvanbruegge  can you start building up the context for these issues such as what you're trying to do and how the existing implementations function?  Root-causing that Vec[4] need (and perhaps surfacing why vulkano-shaders macro didn't pick it up) would be a good start.

**Comment by knappador** [comment]
Another tracking issue that could guide investigation:
https://github.com/vulkano-rs/vulkano/issues/1039

**Comment by jvanbruegge** [comment]
I discovered this while doing an assignment. I had [this simple shader](https://github.com/jvanbruegge/rust-raytracer-assignment/blob/cf823dddf7d0816d4d94a878c63fbae296b0d1d5/shaders/fragment.glsl#L18) that has an array of `vec3`. But on the Rust side, [I have to use an array of 4 floats](https://github.com/jvanbruegge/rust-raytracer-assignment/blob/cf823dddf7d0816d4d94a878c63fbae296b0d1d5/src/object_loader.rs#L6) or I get alignment issues. I did binary search on the data (using the shader to output red or green depending if I am above or below the guessed number) and compared that with the data Rust was sending. The first vector was correct, but the x of the second vector was actually the y. The x was put in the place of the w of the first vector, shifting all the data (that took me a few hours). Then I simply used four floats and [filled the w with zero](https://github.com/jvanbruegge/rust-raytracer-assignment/blob/cf823dddf7d0816d4d94a878c63fbae296b0d1d5/src/object_loader.rs#L6).

**Comment by knappador** [comment]
Let me confirm my understanding.

1.  The shader layout expects vec3's
2.  If you give only vec3's to `ImmutibleBuffer` and then the descriptor set, the layout of the information is wrong.  The data is packed like vec3's in the array but being read like vec4's (and garbage at the end?).
3.  This situation has been observed for vec2's as well?

The first thing that catches my attention is that the Pipeline is created with shader entry points, but the descriptor set, which those shaders tightly depend upon, is only fed into the draw commands some time later.  I'm assuming for now that the descriptor set has no idea what the shader layout expects and knows only what is fed into it.

The descriptor set might need to emit some command to change the size of the buffer strides / elements so that indexes that feed your shader program align correctly.  Since the descriptor set can only trust the size of the buffer type and probably doesn't know what shader it will feed, see what you can find about these two data paths:

1.  Is the descriptor set correctly giving a buffer of vec3 packed as vec3 (can inspect with some transfer functions like in the vulkan guide to save an image) and indicating that it wants to be read as vec3?
2.  Does the shader module get introspected by the pipeline or itself emit some command indicating it wants to read vec4 (or perhaps the default is vec4 for all vecN?).  Are we neglecting to emit such a command at all?

**Comment by knappador** [comment]
Found some alignment information here in the Vulkan docs:

https://vulkan-tutorial.com/Uniform_buffers/Descriptor_pool_and_sets#page_Alignment_requirements

**Comment by jvanbruegge** [comment]
Almost correct, see this:
```
Rust side:   x1 y1 z1  x2  y2 z2 x3  y3  z3
Shader side: x1 y1 z1 (w1) x2 y2 z2 (w2) x3
```
So yeah, the data is all there, but as the shader declares them as `vec3` the `w` is not accessable.
I have not tried vec2.

From the link you shared might come the explanation:
> A vec3 or vec4 must be aligned by 4N (= 16 bytes)

So when just passing `[float; 3]` the values are not aligned with 4N

**Comment by knappador** [comment]
> The x was put in the place of the w of the first vector,

This looks like a packing issue, and I'm expecting that the memory on the GPU looks like:

```
GPU memory: x1 y1 z1 x2 y2 z2
```
Where the stride is 12 bytes and the docs say we need 16 bytes.  I want to blame the buffer, but it doesn't know it's being used in a descriptor set at the time of creation, so it wouldn't know it needs to adjust its stride with some padding.

Just above, where you show:
```
Shader side: x1 y1 z1 (w1) x2 y2 z2 (w2) x3
```
This looks like the correct way to be packed in graphics memory based on the docs.   Is this the  **corrected** case after you padded on the Rust side?  I'm trying to focus on what is incorrect to know where to go fix the source.

**Comment by jvanbruegge** [comment]
No, with the padding applied on the Rust side (that works):
```
Rust side: x1 y1 z1  0   x2 y2 z2  0   x3 y3 z3 Shader side: x1 y1 z1 (w1) x2 y2 z2 (w2) x3 y3 z3
```

**Comment by knappador** [comment]
And if you don't pad the Rust side, you get
```
Shader side: x1 y1 z1 x2 y2 z2
```
correct?

**Comment by jvanbruegge** [comment]
No, when having two vectors `(1,2,3),(4,5,6)` in Rust, without padding, I get in GLSL the two vectors `(1,2,3),(5,6,X)` where X is random (or 0; can't remeber how GLSL handles uninitialized memory).
If I pad on the rust side `(1,2,3,0),(4,5,6,0)` i get the correct vectors `(1,2,3),(4,5,6)`

**Comment by knappador** [comment]
```
Host mem:   1,  2,  3,  4,  5,  6

GPU memory: 1,  2,  3,  4,  5,  6,  ?,  ?
            |____________|  |___________|
                 |                |
                 |                |
                 |                |
Addressed   [0x0 to 0xf]    [0x10 to 0x1f]
                 |                |
Bound       Vec3[1, 2, 3]    Vec3[5, 6, ?]
```
Rust side underwrites to buffers that will be addressed with stride = 16 bytes.  I believe this is because it doesn't anticipate at the time the buffer is populated that it will be used for a shader.   Perhaps our only option is to type restrict the buffers that can be used for creating descriptor sets and thereby push the constraint up to the initialization.

**Comment by jvanbruegge** [comment]
it would be amazing if we could reflect the GLSL struct into Rust. Then we could use a custom "serializer" that takes care of alignment. I am not sure if this is possible though (more familiar with Haskell than with Rust)

**Comment by knappador** [comment]
> it would be amazing if we could reflect the GLSL struct into Rust. Then we could use a custom "serializer" that takes care of alignment

If you play around with breaking the shader, you'll find some forms that detect misconfiguration and refuse to compile.  I'm not sure what is detected, but we do currently introspect, I believe the SPIR-V form.

This still leaves the issue of doing the padding automatically.  The pipeline object contains the shaders and so you would think that the point of descriptor set creation has enough information to properly decide everything, but it either has to modify or merely enforce the striding via buffer type.

https://github.com/jvanbruegge/rust-raytracer-assignment/blob/cf823dddf7d0816d4d94a878c63fbae296b0d1d5/src/main.rs#L220-L228

**Comment by jvanbruegge** [comment]
I think I found the proper way to fix this (have not been able to test it though).
Annotate structs with `#[repr(C, align(16))]` instead of just `#[repr(C)]`. I did not know about this option before and just learned it from the `rendy` examples
