### ISSUE TITLE
Renderpass attachments always created with VK_ATTACHMENT_LOAD_OP_CLEAR

### ISSUE THREAD

**Issue by Bunogi** [vulkano-rs/vulkano#1191]
# Template

*   Version of vulkano: 0.11.1
*   OS: Void Linux x64 glibc
*   GPU (the selected PhysicalDevice): AMD RADV POLARIS10 (LLVM 7.0.1)
*   GPU Driver: amdgpu
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: https://pastebin.com/F7vXmPyy

# Issue

When defining a render pass using `vulkano::single_pass_renderpass`, the attachment load op gets set to `VK_ATTACHMENT_LOAD_OP_CLEAR` even if load has been specified. I verified this using renderdoc. The relevant passes are prepended with `other_` for clarity.

**Comment by knappador** [comment]
I see the creation of the renderpass.

```Rust
    let other_renderpass = Arc::new(
        single_pass_renderpass!(
            device.clone(),
            attachments: {
                color: {
                    load: Load,
                    store: Store,
                    format: swapchain.format(),
                    samples: 1,
                }
            },
            pass: {
                color: [color],
                depth_stencil: {}
            }
        )
        .unwrap(),
    );
```
Just in API terms, I believe the value should be visible in logged output.  I'll have to get something like renderdoc set up to be able to evaluate a fix.

In terms of what might actually be broken, something about the size-dependent setup strikes me as possibly related since it's only consuming one of the render passes at the call site.   I'll play around with this after I burn down my PR stack a bit.  Happy to evaluate any fix proposals or verify findings until then.

**Comment by Rua** [comment]
Is this still an issue?
