### ISSUE TITLE
Adding a new maintainer

### ISSUE THREAD

**Issue by mitchmindtree** [vulkano-rs/vulkano#1241]
Recently @Eliah-Lakhin got in touch via email and expressed interested in helping with maintenance of the vulkano-rs repos - I think it goes without saying that vulkano could absolutely use the assistance!

@rukai @tomaka if this sounds OK, could either of you add @Eliah-Lakhin to the vulkano-rs org? I don't believe I have the permissions to do so.

**Comment by rukai** [comment]
Vulkano is in a really unfortunate position where due to lack of maintenance its impossible for potential contributors to prove they are capable maintainers.

I was able to find just one contribution from eliah-lahkin to other rust projects: https://github.com/tokio-rs/tokio/pull/1433/files
I'm not really convinced he should be added to the org.

I would recommend anyone who thinks they are capable of maintaining vulkano to instead consider, using and contributing to wgpu. It has a bright future ahead of it, and you wont be stuck maintaining vulkano which, believe me is a very complicated code base.
Dont forget that wgpu has first class support for native applications, its not just for web!

This is probably not the answer you want to hear.
Sorry.

**Comment by Eliah-Lakhin** [comment]
@mitchmindtree, @rukai First of all I want to say thank you guys for reviewing my candidacy.

You are right, I don't have enough expertise to be able to take an active role in Vulkano core development myself yet. The problem is that there are those who have such expertise and want to contribute, but don't want to lead code review. And the current maintainers not able to review on regular basis too. My motivation was to give a help in managing of the pending PRs only, because I'm a user of this library and I'm interested in continuation of it's maintenance.

Talking about wgpu, this is very impressive and promising project, but in my humble opinion it is in too early stage of development to be a suitable candidate for Vulkano replacement. At least not for all users. As such some of the users are in a bad situation when they are forced to migrate to wgpu by Vulkano maintainers, but practically can't perform this migration.

I hope this deadlock will be resolved eventually.

**Comment by mitchmindtree** [comment]
Just wanted to quickly mention `wgpu` does indeed have some limitations compared to `vulkano`, you can find some discussion comparing the suitability of wgpu and rendy for use within here nannou-org/nannou#374 if interested. I do agree with rukai though that `wgpu` at least seems to have a much brighter future than `vulkano` in terms of maintenance and progress.

**Comment by AustinJ235** [comment]
I would be willing to be a maintainer. I actively depend on vulkano for my basalt project. I have contributed some in the past and am continuing to increase my knowledge of vulkan.

**Comment by Eliah-Lakhin** [comment]
> I do agree with rukai though that wgpu at least seems to have a much brighter future than vulkano in terms of maintenance and progress.

@mitchmindtree Well, Vulkano maintenance is all in our hands. To be more specific, it is in hands of @rukai who has a power to block entire project. I wouldn't say there is any resistance from the community. Moreover I see some enthusiasm to move the project forward which is blocking by a purely "bureaucracy" reasons.

As of wgpu. The project will bright as long as @kvark has enthusiasm to develop it. Once he left, wgpu becomes semi-dead zombie. And we will experience the same issues we currently have with Vulkano if not worth. So I would fight for the long-term support of Vulkano instead. At least it passed test of time, and have a more clear basis than wgpu.

**Comment by rukai** [comment]
I have given access to AustinJ235.
I can see from your basalt project you are clearly invested in vulkano!
Good luck.
