### ISSUE TITLE
raw instance extensions are not visible in loaded_extensions

### ISSUE THREAD

**Issue by heeen** [vulkano-rs/vulkano#1253]
# Template

*   Version of vulkano: 0.14
*   OS: Linux
*   GPU (the selected PhysicalDevice): GeForce RTX 2080 (type: DiscreteGpu)
*   GPU Driver: 435
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: 
```
use vulkano::instance::{Instance, PhysicalDevice, RawInstanceExtensions};
use std::ffi::{CString};

fn main() {
    let raw_ext =  RawInstanceExtensions::new( 
        [
            "VK_KHR_external_memory_capabilities",
            "VK_KHR_external_semaphore_capabilities",
//            "foobar",
         ].iter().map(|&s| CString::new(s).unwrap())
    );

    let instance = match Instance::new(None, raw_ext, None) {
         Ok(i) => i,
         Err(err) => panic!("Couldn't build instance: {:?}", err)
    };

    let physical = PhysicalDevice::enumerate(&instance).next().unwrap();
    println!("Using device: {} (type: {:?})", physical.name(), physical.ty());
    println!("extensions: {:?}", instance.loaded_extensions());
}
```
# Issue

extensions selected via RawInstanceExtensions are not shown in loaded_extensions:
Using device: GeForce RTX 2080 (type: DiscreteGpu)
extensions: []

there is a conversion from RawInstanceExtensions to InstanceExtensions here:
https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/instance/instance.rs#L287 where the unknown extensions are lost.
could Instance::extensions also be RawInstanceExtensions?
https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/instance/instance.rs#L98

**Comment by AustinJ235** [comment]
Ok I think the problem here is that you are not loading the required extensions.

The examples include:
```
let extensions = vulkano_win::required_extensions();
let instance = Instance::new(None, &extensions, None).unwrap();
```

``extensions`` is of the type ``InstanceExtensions``. Since you want custom extensions loaded you need to use the type ``RawInstanceExtensions``. Conveniently ``From<InstanceExtensions>`` is implemented for ``RawInstanceExtensions``.

So your code should look something like this:
```
let mut extensions: RawInstanceExtensions = vulkano_win::required_extensions().into();
extensions.insert("VK_KHR_external_memory_capabilities");
extensions.insert("VK_KHR_external_semaphore_capabilities");
let instance = Instance::new(None, &extensions, None).unwrap();
```

Let me know if you have further problems or issues. I have not tested this myself.

**Comment by AustinJ235** [comment]
Looking further at this I realize the ``insert`` function takes ``CStrings``. This isn't very convenient. I may open a pull request to add a function akin to:
```
vulkano_win::required_extensions_and<T: IntoIterator<Item = &'a str>>(extra: T)
```

**Comment by heeen** [comment]
@AustinJ235 , I fixed your example code to compile like this:

```
    let ex = vulkano_win::required_extensions();
    let mut extensions: RawInstanceExtensions = (&ex).into();
    extensions.insert(CString::new("VK_KHR_external_memory_capabilities").unwrap());
    extensions.insert(CString::new("VK_KHR_external_semaphore_capabilities").unwrap());

    let instance = match Instance::new(None, extensions, None) {
         Ok(i) => i,
         Err(err) => panic!("Couldn't build instance: {:?}", err)
    };
```
> Using device: GeForce RTX 2080 (type: DiscreteGpu)
> extensions: [VK_KHR_surface, VK_KHR_xlib_surface, VK_KHR_xcb_surface, VK_KHR_wayland_surface]
> layers: Iter([])


however you will notice that the additional extensions are still not represented. The conversion from RawInstanceExtensions to InstanceExtensions drops anything that InstanceExtensions does not know about.
Also, for this tool I don't necessarily want windowing at all, it is supposed to be a headless renderer, hence I don't want to use vulkano_win.

**Comment by AustinJ235** [comment]
So looking at the code it would appear that yes the list of strings given when creating the instance is converted into ``InstanceExtensions`` after the instance has been created; however, I think the extensions should be still loaded, just not listed when you query. So currently there is no way of querying the vulkano instance about custom loaded extensions.

**Comment by AustinJ235** [comment]
I think a viable path for solving this would be storing the ``RawInstanceExtensions`` instead of ``InstanceExtensions`` within the instance struct and when the user calls ``loaded_extensions()`` it would convert ``RawInstanceExtensions`` into ``InstanceExtensions`` then. Then another function would be added eg ``raw_loaded_extensions()`` that would return the ``RawInstanceExtensions`` within the instance.

**Comment by heeen** [comment]
How much of an API break would it be if loaded_extensions returned RawInstanceExtensions instead?
And by the way, the fix we come up with should also be done for device extensions

**Comment by AustinJ235** [comment]
Right now it is already an api break. I dont like returning the raw version is a good idea. Really all that is happening in the backend with this is the list you provide at creation is just stored in the instance struct with no real purpose other than to provide the user a way to query what they already know. So really there isn't a point to storing it at all.

**Comment by AustinJ235** [comment]
I think the original intent might have been to have optional features that require certain deps to be loaded and this would provide a way for vulkano to check what the instance was created with. So that being said I think keeping the original idea in place and maybe providing an ``additional`` field to the ``InstanceExtensions`` struct with a list of the vulkano unaware extensions wouldn't be a bad idea. Doing this would then remove the need to even have ``RawInstanceExtensions`` at all.

I'll think about it some more on what I want to do, but in general the current api is kinda clunky, so we can certainly do something about it to improve it.
