### ISSUE TITLE
Shader codegen always treats descriptors as readonly

### ISSUE THREAD

**Issue by RobinMcCorkell** [vulkano-rs/vulkano#1264]
Vulkano 0.14

I have a GLSL file with some readonly descriptors and some not, however the code generated by vulkano-shaders marks all of the descriptors as readonly. This has knock-on effects like the pipeline barrier code not working, since it looks for buffers that are not readonly in order to generate barriers in the right places.

It seems like vulkano-shaders always considers descriptors to structs (and by rule induction, buffers too) as readonly, which doesn't seem correct: https://github.com/vulkano-rs/vulkano/blob/master/vulkano-shaders/src/descriptor_sets.rs#L203

**Comment by Ziqul** [comment]
Any recepie for workaround?

**Comment by Rua** [comment]
I just ran into this bug myself. Vulkano-shader always sets the `readonly` attribute on the descriptors it generates to `true`, whether the shader writes to it or not. This has knock-on effects for memory safety in `SyncCommandBufferBuilder`: since the builder thinks the buffer isn't being written, it doesn't insert a pipeline barrier between the write and any subsequent reads, leading to a data race on the GPU.
