### ISSUE TITLE
Pipeline barriers are not inserted in the right places due to stale hashmap key

### ISSUE THREAD

**Issue by Xenopathic** [vulkano-rs/vulkano#1265]
If the same resource is used in two commands, Vulkano will correctly put a pipeline barrier between the commands. If it is used in a third command however, Vulkano will not put a second pipeline barrier in. This can be easily demonstrated by dispatching the same compute shader and descriptor set multiple times.

The problem lies in the `resources` hashmap, used by `SyncCommandBufferBuilder::prev_cmd_resource()`. Vulkano only decides to insert a pipeline buffer (and flush the command queue) if the collision command ID is greater or equal to the first unflushed command ID, i.e. the colliding command has not been flushed. However, the colliding command is inferred from the hashmap, which references the *first* command that used a given resource, so after the first flush for a resource, any future uses of the command are incorrectly assumed to have already been flushed, so pipeline barriers are not inserted.

One fix is to update the command ID inside the hashmap key to the latest command ID (which, by construction, also conflicts with the resource), but this doesn't seem super clean. I think this code needs a rethink and a refactor to move the command ID into the value, rather than the key.

**Comment by AustinJ235** [comment]
I have confirmed that a long standing bug in my Basalt framework is caused by this: https://github.com/AustinJ235/basalt/issues/6

I have already had a look at the code to see if I can understand what is going on. I agree with the author that some rethinking needs to be done with this code.

In order for me to fix this issue I will need to understand vulkan a little better to create a proper fix. If anyone has more experience in this area pull requests are welcome.

**Comment by AustinJ235** [comment]
I have been going through the code some more learning the process of how this stuff works. I think just updating the command id is out of question. 

From what I understand right now when a command adds a resource that already exists it creates a key, but the key isn't very unique so it grabs whatever entry had that resource first which is going to contain the command id of whichever command created the key in the first place. So what is happening here is that when a second command uses the resource it doesn't update the command id at all so when a third one is added it doesn't know to insert a barrier because as far as it is concerned there are no conflicting commands in the pending commands.

So in reality command_id should really be a list of all the commands that this resource has been used in. If it were a value it would be a matter of just changing the types around, but since it is a key it kinda makes matters a bit more difficult.

We could still use a hashmap but instead of a key based on a struct of what really should be a value we could use the conflict_key() function of the resources to be used a key. This would still allow for a more optimized route over just a list of these structs.

With the struct being a value instead of a key, when we add a resource we check if it conflicts, if it does we flush the pending commands, and add then add the new command_id to the val. Then it would be a matter of instead of just checking one command_id for conflicts we would have to check all the command listed.

**Comment by YaLTeR** [comment]
I think I'm hitting a similar issue where I have two dispatch calls to two different compute shaders in one command buffer, where the first one writes to a buffer and the second one reads from it, and there's no pipeline barrier call between the two according to RenderDoc. The code looks like this:
```rust
let layout = self.pipeline.descriptor_set_layout(0).unwrap();
let set = PersistentDescriptorSet::start(layout.clone())
    .add_buffer(prev.clone())
    .unwrap()
    .add_buffer(curr.clone())
    .unwrap()
    .add_buffer(next.clone())
    .unwrap()
    .build()
    .unwrap();

let vertex_layout = self.vertex_pipeline.descriptor_set_layout(0).unwrap();
let vertex_set = PersistentDescriptorSet::start(vertex_layout.clone())
    .add_buffer(next.clone())
    .unwrap()
    .add_buffer(self.vertex_buffer.clone())
    .unwrap()
    .build()
    .unwrap();

let command_buffer =
    AutoCommandBufferBuilder::new(self.device.clone(), self.queue.family())
        .unwrap()
        .dispatch(
            [SIZE, SIZE, 1],
            self.pipeline.clone(),
            set,
            self.drop.take().unwrap_or((-1., -1.)),
        )
        .unwrap()
        // vulkano doesn't insert a barrier here for some reason?
        .dispatch(
            [SIZE, SIZE, 1],
            self.vertex_pipeline.clone(),
            vertex_set,
            (),
        )
        .unwrap()
        .build()
        .unwrap();
let future = command_buffer.execute(self.queue.clone()).unwrap();
future
    .then_signal_fence_and_flush()
    .unwrap()
    .wait(None)
    .unwrap();
```

**Comment by AustinJ235** [comment]
If you believe this bug is the issue go ahead and try out this pull request: https://github.com/vulkano-rs/vulkano/pull/1290

I know modifying the code that entering another render pass will add a barrier, but not sure about dispatches. It would make sense to not add them for dispatches as maybe the user would want to run them at the same time maybe? I could look into adding a function to auto command buffer to explicitly add a barrier where the user requests.

**Comment by AustinJ235** [comment]
So looking around the code pertaining to dispatches. It looks as if there is no regard to if a resource was previous used. I feel like just automatically inserting a barrier isn't appropriate either. At this time I don't think this would classify as a bug necessarily just unimplemented safety checks. For now I'd recommend using two separate commands like this:
```
AutoCommandBufferBuilder::new(self.device.clone(), self.queue.family())
    .unwrap()
    .dispatch(
        [SIZE, SIZE, 1],
        self.pipeline.clone(),
        set,
        self.drop.take().unwrap_or((-1., -1.)),
    )
    .unwrap()
    .build.unwrap()
    .execute(self.queue.clone()).unwrap()
    .then_signal_fence_and_flush().unwrap()
    .then_execute(self.queue.clone(), AutoCommandBufferBuilder::new(self.device.clone(), self.queue.family())
        .unwrap()
        .dispatch(
            [SIZE, SIZE, 1],
            self.vertex_pipeline.clone(),
            vertex_set,
            (),
        )
        .unwrap()
        .build()
        .unwrap()
    )
    .unwrap()
    .then_singal_fence_and_flush()
    .unwrap()
    .wait(None)
    .unwrap();
```

**Comment by AustinJ235** [comment]
As this isn't pertaining to this bug I have opened a new issue for this here: https://github.com/vulkano-rs/vulkano/issues/1297
