### ISSUE TITLE
triangle.rs example not working

### ISSUE THREAD

**Issue by ThibaudDauce** [vulkano-rs/vulkano#1293]
*   Version of vulkano: 0.16.0
*   OS: ArchLinux
*   GPU (the selected PhysicalDevice): Intel

# Issue

The [`triangle.rs`](https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs) was not working on my computer:
```
error[E0308]: mismatched types
   --> src/main.rs:167:38
    |
167 |             PresentMode::Fifo, true, ColorSpace::SrgbNonLinear).unwrap()
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found enum `vulkano::swapchain::capabilities::ColorSpace`
    |
    = note: expected type `std::option::Option<&std::sync::Arc<vulkano::swapchain::swapchain::Swapchain<winit::Window>>>`
               found type `vulkano::swapchain::capabilities::ColorSpace`

error: aborting due to previous error
```

I just changed `ColorSpace::SrgbNonLinear` to `None` and it works but I'm not sure it's the right thing to do. I don't know where I need to put the `ColorSpace` information.

If it's the right modification, I can push a PR to update the example.

**Comment by AustinJ235** [comment]
The examples in the repo are for the latest master version and are not compatible with the released versions. This is a breaking change that will be coming in the next version. In the current released version it is expected that you provide the previous swapchain if there was one that is why it is an option. In the latest master you just need to specify the colorspace instead of passing the old swapchain.

**Comment by ThibaudDauce** [comment]
Hi,

Thanks, I didn't find a tag on Github to see the 0.16 version of the example. But the working examples are available on https://github.com/vulkano-rs/vulkano-examples/.
