### ISSUE TITLE
i3wm examples: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfHostMemory'

### ISSUE THREAD

**Issue by CallumDowling** [vulkano-rs/vulkano#1324]
*   Version of vulkano: 0.17 (#de2ef7)
*   OS: Ubuntu 19.04
*   GPU (the selected PhysicalDevice): GTX 1080
*   GPU Driver: Nvidia proprietary 440.26
*   Vulkan Instance Version: 1.1.97
*   i3 Version: 4.16.1

Got this error on all of the examples that have a window when using i3wm.
The windows renders for about 1-2 seconds, locks up, then auto closes in about 5 seconds.

The teapot animation really laggy. 

When I switch back to the default gnome, all example work fine, teapot is smooth.

**Comment by AustinJ235** [comment]
if you call wait after the fence does the problem still occur?

**Comment by CallumDowling** [comment]
Triangle is fixed after wait, thanks!
```
match future {
    Ok(future) => {
        let _ = future.wait(None);
        previous_frame_end = Some(Box::new:(future) as Box<_>);
};
...
```
Teapot works only when I run it from a window that has focus (default mod f), if run from a console without focus, thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedDimensions'

**Comment by AustinJ235** [comment]
We used to have that workaround in the examples, but I thought the issue resolved itself when I fixed the pipeline barrier issue. Is 440 the latest stable version of the driver or is that a legacy branch?

**Comment by CallumDowling** [comment]
Latest stable according to ubuntu-drivers.

**Comment by AustinJ235** [comment]
`UnsupportedDimensions` should be a recoverable error. Which function is returning that? All that should be needed is for the swapchain to be recreated.

**Comment by CallumDowling** [comment]
```
Swapchain::new(device.clone(), surface.clone(), caps.min_image_count, format, dimensions, 1,
 73             usage, &queue, SurfaceTransform::Identity, alpha, PresentMode::Fifo,
 74             FullscreenExclusive::Default, true, ColorSpace::SrgbNonLinear).unwrap()
```

**Comment by AustinJ235** [comment]
The error returning there suggests that what `surface.window().inner_size()` is returning is out of date. In my personal code of Basalt I use something akin to
```
surface.capabilities(physical).unwrap().current_extent.unwrap_or(surface.window().inner_size().into())
```
which gets the dimensions preferably directly from the surface itself rather then from the window. I think that maybe in the examples we choose this method of getting the dimensions as some drivers may not having the current extent available, which is why I think I have the fallback to the window's inner_size there.

Calling capabilities does have the caveat of needing access to the physical device which is generally not very friendly to store in a struct, so it is dropped in those use cases. If that is the case, you can either store the physical device's index after you obtain it and then use `PhysicalDevice::from_index()` to obtain it back to get the capabilities, or probably more safely store the uuid of the physical device and then find it on the iterator from `PhysicalDevice::enumerate()`.

**Comment by CallumDowling** [comment]
Replaced dimensions call with your Basalt line and it worked for me. 
Thanks!
