### ISSUE TITLE
Crash when create swapchain  on KBL

### ISSUE THREAD

**Issue by t18b219k** [vulkano-rs/vulkano#1341]
*   Version of vulkano: 0.18.0
*   OS: ubuntu20.04 beta
*   GPU (the selected PhysicalDevice): Intel(R) HD Graphics 620 (KBL GT2)
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: vulkano/examples/bin/teapot/main.rs or any 

# Issue
 Swapchain::new() return s Result::Err(OomError(OutOfHostMemory)) when create swapchain on this gpu and this os version.
P.S.
 on kwin_wayland
crash is not comfirmed kwin_x11

**Comment by jeffw387** [comment]
I suspect this is the same as issue #1318, and I submitted pull request #1339 to fix it.

**Comment by AustinJ235** [comment]
As hinted by others there may be an issue with the format not being supported. You can check with a vulkan caps viewer, https://vulkan.gpuinfo.org/download.php . Although you are using `let format = caps.supported_formats[0].0;` so there may be an issue with vulkano here returning formats that are not supported. I'd go ahead and try a few other formats and see if this is the issue then we can look to resolve the issues with vulkano when we have more of a context.

**Comment by maximbaz** [comment]
Trying out vulkano with triangle example, I have a similar issue:

```
Using device: Intel(R) Iris(R) Plus Graphics (ICL GT2) (type: IntegratedGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OomError(OutOfHostMemory)', src/bin/triangle.rs:156:9
```

With PR #1339 I do indeed get that new error about image configuration:

```
Using device: Intel(R) Iris(R) Plus Graphics (ICL GT2) (type: IntegratedGpu)
Image properties not supported. FormatNotSupported
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedImageConfiguration', examples/src/bin/triangle.rs:177:9
```

Printed out the full list of `caps.supported_formats`:

```
Format: [(B8G8R8A8Srgb, SrgbNonLinear), (B8G8R8A8Unorm, SrgbNonLinear)]
```

Tried both formats, and getting the exact same error.

A driver issue? 🤔 

I'm also on Wayland, if that matters (sway, arch linux)

**Comment by AustinJ235** [comment]
I don't have access to any intel graphics chips, so sadly I am not able to test for myself. Are you getting the same `UnsupportedImageConfiguration` error with the other format? Also refer to a vulkan capabilities view tool. I believe there is a linux version available. I don't know if the supported list from the swapchain is to be trusted. May they are supported, but with different usage.

**Comment by AustinJ235** [comment]
So with https://github.com/vulkano-rs/vulkano/issues/1318 merged. I am also running into the `UnsupportedImageConfiguration`. Modifying what is returned from the capabilities by doing this:

```rust
ImageUsage {
	storage: false,
	.. swap_caps.supported_usage_flags
},
```
appears to solve the conflicting usage. Would there ever be a use case where the `storage` usage would need to be enabled, but that aside this is option appears to be coming directly from vulkan: https://github.com/vulkano-rs/vulkano/blob/57c545d7aba653a4dc99648a5a8892bbb538b539/vulkano/src/swapchain/surface.rs#L548

later copied to the output here: https://github.com/vulkano-rs/vulkano/blob/57c545d7aba653a4dc99648a5a8892bbb538b539/vulkano/src/swapchain/surface.rs#L631

so there doesn't appear to be any modification on our part. Maybe the implementation is saying that this usage is supported in general, but not for specific formats? Not sure how we go about this.

We could remove the `supported_usage_flags` field as it seems to be generalized for all formats, and we just have the user manually construct `ImageUsage` with the usages they intend to use. Maybe provide a helper construct on `ImageUsage` such as `ImageUsage::swapchain()`, because frankly the image usage returned from this seems very open. For example on my system:

```
ImageUsage {
    transfer_source: true,
    transfer_destination: true,
    sampled: true,
    storage: true,
    color_attachment: true,
    depth_stencil_attachment: false,
    transient_attachment: false,
    input_attachment: false,
}
```
Lets break it down.
- `transfer_source` would be when the user would want to copy the swapchain image. The only utility I could see for this is if they wanted to have some screenshot option. 
- `transfer_destination` would only be used where you are not rendering directly to the swapchain, such as copying other buffer(s) & image(s) onto it.
- `sampled` this one is a bit out there for use cases, say maybe a screenshot option that does some sort of post processing. I have a hard time trying to think of another use case.
- `storage` is kinda similar to sampled in a sense. As it just enables usage for reading/writing to the image without going through a sampler.
- `color_attachment` this one is obviously required for 99% of use cases is probably required by spec to be supported. It however wouldn't be required for use of `transfer_destination`.

So with that said, maybe would could just have another field on the caps such as `minimal_usage_flags` which would just be `ImageUsage` with just `color_attachment` enabled.

I see this issue as needing to be resolved before the next release of vulkano.

**Comment by AlaricSenat** [comment]
I've tried to wrap my mind around the issue and made a minimal cpp example that reproduced the failure and it seems that yeah, passing the `supportedUsageFlags` to `vkGetPhysicalDeviceImageFormatProperties()` is a pretty bad idea !
That's probably due to the fact that even if theoretically the `vkSurface` supports an usage, it might not be implemented on all images formats or even none at all in my case.

I like the idea of a `minimal_usage_flags` function that would only set `color_attachment` to `true` but it seems to me it would be considered 'minimal' only if the surface we deal with is a window...

Since there is already a bunch of creation helper functions in `ImageUsage` (`::none()` and `::all()`) the simplest way might just be to let things like they are in vulkano and adapt the examples to make them only use the `color_attachment` usage instead of the whole set of supported usages by the surface !

What do you think ? I've got some time ahead so i'll gladly adapt the examples !

**Comment by t18b219k** [comment]
ok It works fine .
thanks
