### ISSUE TITLE
I want to Clear depth buffer separately

### ISSUE THREAD

**Issue by t18b219k** [vulkano-rs/vulkano#1432]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.19.0
*   OS: Ubuntu 20.04
*   GPU (the selected PhysicalDevice): Intel HD 620
*   GPU Driver: Mesa 20
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

Please describe the issue and provide anything at all that will help us resolve it.

**Comment by AustinJ235** [comment]
Feel free to elaborate on this issue some more. In the `ordered_passes_renderpass!` and `single_pass_renderpass!` macros their should be a `load` field in the attachment. Have you tried playing with that field? Otherwise you could also run a `clear_color_image` command from `AutoCommandBufferBuilder` to clear the specific attachment.

**Comment by t18b219k** [comment]
if i manage stencil buffer as R8Uint ,depth as R32Sfloat and set to renderpass 
it might be fine
