### ISSUE TITLE
[Feature Request] ImageUsage parameter on ImmutableImage::from_iter

### ISSUE THREAD

**Issue by faulesocke** [vulkano-rs/vulkano#1446]
The `ImmutableImage::from_iter` internaly calls `from_buffer` which then creates the image with usage flags `transfer_destination` and `sampled`. However, sometimes one might want to specify more usage flags, for example `transfer_source` to use the image as a source for blit operations.

My suggestion is the following: There should be a `usage` parameter to both methods and it's fine to give `ImageUsage::none()` there. Internally the `from_buffer` method creates the correct usage with the following code:
```rust
let usage = ImageUsage {
    transfer_destination: true,
    sampled: true,
    .. usage
};
```

Of course this is a breaking API change so before I implement this and open a PR I would like to ask if it would be accepted for the next release.

Other options would be:
- provide two new methods `from_iter_with_usage` and `from_buffer_with_usage`. This would not be a breaking change.
- do nothing and leave this problem to the user

**Comment by Eliah-Lakhin** [comment]
@faulesocke Sounds good, let's proceed with implementation. Can you work on it?

I would go with the first non-breaking option of creating two new additional methods you suggested. And the existing one would reuse these two new internally. So the feature will be non-breaking, and the user will be able to choose between default implementation and customized ones.

**Comment by faulesocke** [comment]
Okay, while implementing I noticed this above `from_buffer`:
```rust
    /// TODO: Support mipmaps
```

I can implement this as well but there are multiple ways on how we can do it:

1. assume the data for all mipmaps is in the buffer. Then this is just a copy operation
2. assume the buffer only contains the first mip level. In this case we need to generate the other levels on the fly, using blit operations. There is currently a bug in vulkano (#1441) that prevents generating blit commands where source and destination is the same image, so if we go with option 2 this needs to get fixed first. Since #1441 is similar to my other issue #1447 I will probably start working on that.

**Comment by Eliah-Lakhin** [comment]
@faulesocke Well, ideally we should support all possible cases: a) A method without mipmaps support(the current `from_buffer` implementation); b) A method for buffer with all mipmaps inside ready to use; c) And the most generic one -- a method that will be able to construct mipmaps on the fly from the buffer containing data for only a single layer. But I would divide it into three distinct functions, so the end user will have a choice.

Regarding the cross-layers bliting blocker please also take a look at the work-in-progress PR from @Gosuo : https://github.com/vulkano-rs/vulkano/pull/1449

**Comment by Eliah-Lakhin** [comment]
Just for tracking. #1449 is merged now, so the blocker is probably resolved.

**Comment by Rua** [comment]
I don't think #1449 is the blocking issue. Rather, it has to do with how the conflict detection functions on the `ImageAccess` trait are implemented. Currently they treat anything as a "conflict" if the two images are the same, regardless of whether the regions being affected by the operation overlap. These implementations also assume no memory aliasing, so if images are distinct, or if the other object is a buffer, then no conflict is assumed.

Fixing the situation may not be as simple as changing the conflict test, because you have to take into account layout changes. If an operation writes to a subregion of an image and changes the layout of that particular region, then that affects the validity of the rest of the image. Vulkano is currently written to rely on the whole image having a particular layout, so allowing layout transitions on a subregion would break things quite severely. Of course, if you're blitting from one part to another and not changing the layout, that's not a problem, but any changes made to conflict detection would need to take into account the possibility of writes  that change layouts.
