### ISSUE TITLE
Version bump to 0.20.0

### ISSUE THREAD

**Issue by Eliah-Lakhin** [vulkano-rs/vulkano#1461]
@AustinJ235 Hi Austin.

We probably have enough unreleased features in `master` to make another version bump to `0.20.0`, and to publish them to crates.io:

https://github.com/vulkano-rs/vulkano/blob/master/CHANGELOG_VULKANO.md
https://github.com/vulkano-rs/vulkano/blob/master/CHANGELOG_VK_SYS.md

What would be the next steps to perform the release?

**Comment by AustinJ235** [comment]
Previously releases were done automatically through Travis when the version was bumped on master. I don't have access to release.  So we'd need @tomaka to grant us owner rights to the crates or to have him publish it for us.

**Comment by Rua** [comment]
Haven't we learned from this year that 20 is evil? :D

**Comment by Eliah-Lakhin** [comment]
@AustinJ235 I did an attempt to bump the version on `master` in hope that Travis is still capable to publish automatically, but it fails: https://travis-ci.org/github/vulkano-rs/vulkano/builds/751556631

@tomaka If you don't mind I could manage publishing to crates.io manually. My account associated with crates.io is https://github.com/jht-maintenance . Thank you, and I'm sorry we have to disturb you again. :/

**Comment by AustinJ235** [comment]
``
error: api errors (status 401 Unauthorized): The given API token does not match the format used by crates.io. Tokens generated before 2020-07-14 were generated with an insecure random number generator, and have been revoked. You can generate a new token at https://crates.io/me. For more information please see https://blog.rust-lang.org/2020/07/14/crates-io-security-advisory.html. We apologize for any inconvenience.
``

I fixed the whitespace issue with travis, but now the publish is failing because the token on travis is outdated.

**Comment by tomaka** [comment]
Hi! Sorry, I'm not very responsive to GitHub notifications. Emailing me works.

I've created a "publishers" team in the `vulkano-rs` organization that includes you @Eliah-Lakhin and @AustinJ235, and granted them publishing rights for `vulkano`, `vulkano-win`, `vulkano-shaders`, and `vk-sys`.

**Comment by AustinJ235** [comment]
Thank you! Happy holidays!

@Eliah-Lakhin I went ahead and published the crates.
