### ISSUE TITLE
Image example: Image is heavily saturated.

### ISSUE THREAD

**Issue by i509VCB** [vulkano-rs/vulkano#1468]
I copied in the image example to learn my way around vulkan and I noticed the image that is rendered is saturated more than it should be.

*   Version of vulkano: 0.20.0
*   OS: Arch Linux
*   GPU (the selected PhysicalDevice): `Nvidia GTX 1060 Mobile` (Tried also on another laptop with a `Intel Corporation Iris Plus Graphics G1 (Ice Lake) (rev 07)` but it seems to generate confetti - might need to fight with drivers here)
*   GPU Driver: proprietary nvidia linux driver
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: See image example. When setting background to white the rust logo is definitely too saturated.

**Comment by Luminiscental** [comment]
This likely happens because the swapchain image format often gets picked as Snorm/Unorm, whereas the colorspace is picked as Srgb (and the shaders aren't doing a manual conversion).

Replacing the code that chooses the swapchain image format
```rs
let format = caps.supported_formats[0].0;
```
with
```rs
let is_srgb = |format| matches!(format, Format::R8Srgb
    | Format::R8G8Srgb
    | Format::R8G8B8Srgb
    | Format::B8G8R8Srgb
    | Format::R8G8B8A8Srgb
    | Format::B8G8R8A8Srgb
    | Format::A8B8G8R8SrgbPack32);
let format = caps.supported_formats.iter()
    .map(|p| p.0)
    .find(|&f| is_srgb(f))
    .unwrap();
```
gives accurate color values on my machine. I guess it's possible that some devices don't support an Srgb image format for the swapchain, in which case colorspace conversion in the fragment shader would be needed.
