### ISSUE TITLE
vulkano-shaders breaks when trying to use SPIR-V shader generated by rust-gpu

### ISSUE THREAD

**Issue by p0lunin** [vulkano-rs/vulkano#1493]
Repository with bug: https://github.com/p0lunin/vulkano-rust-gpu-bug

Error from proc-macro:
```
error: proc macro panicked
 --> src\main.rs:3:9
  |
3 | /         vulkano_shaders::shader! {
4 | |             ty: "compute",
5 | |             bytes: "target/spirv-builder/spirv-unknown-unknown/release/shader.spv"
6 | |         }
  | |_________^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: ParseError(UnknownConstant("Capability", 5345))
```

I think rust-gpu sets the constant [`Capability`](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_capability_a_capability) to 5345 which denotes the `Vulkan memory model`.

**Comment by Arc-blroth** [comment]
For my own usecase, I've patched this by adding the Vulkan memory model to vk-sys:
```patch
diff --git a/vulkano-shaders/src/enums.rs b/vulkano-shaders/src/enums.rs
--- a/vulkano-shaders/src/enums.rs	(revision b7bcf08424b32923040cb93fb88803ba0976fcdc)
+++ b/vulkano-shaders/src/enums.rs	(revision e2b9203f27cfd3ceb6dc416f80e5a1436e33d491)
@@ -65,6 +65,7 @@
         MemoryModelSimple = 0,
         MemoryModelGLSL450 = 1,
         MemoryModelOpenCL = 2,
+        MemoryModelVulkan = 3,
     } MemoryModel;
 
     typedef enum ExecutionMode_ {
```
Another workaround is to tell [SPIR-V builder to use `MemoryModel::GLSL450`][1] (though this might make the shaders slower).
However, since #1500 would update vulkano's older SPIR-V headers anyway, these workarounds hopefully might not be needed soon :)

[1]: https://github.com/EmbarkStudios/rust-gpu/blob/main/crates/spirv-builder/src/lib.rs#L73

**Comment by Rua** [comment]
I'm going to assume this is no longer an issue, now that the SPIR-V parser is auto-generated.
