### ISSUE TITLE
[Feedback wanted] Should Vulkano panic on validation errors instead?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1546]
Vulkano returns errors from a lot of functions, indicating what are essentially validation errors: something wasn't correct about the arguments. `AutoCommandBufferBuilder` in particular has a huge list of error types, for all of the different operations it can perform.

Thinking about it, though, it seems to me that the user would rarely, if ever, actually _respond_ to any of these errors. If `draw` fails because you provided improper arguments, what would you actually do in this case? You did something dumb, that's not something your application is meant to recover from. It's going to happen every time you run your program. You're supposed to treat it as a bug and fix it.

So I think it's probably better to respond to validation errors with a panic instead of returning a useless error to the user. The user would then not be led to believe that it's an error they actually should handle. Let's face it, you don't. You put `.unwrap()` everywhere and call it a day. Even Vulkano's examples do. Removing all those superfluous error types would also slim down Vulkano's API a fair bit.

Keep in mind, this is specifically about _validation_ errors: errors that can be detected before any call to Vulkan is actually made, determined purely by the arguments of a function. Errors resulting from a Vulkan call after the fact would remain in place, of course.

**Comment by gurchetansingh** [comment]
Hahaha yeah.  I had my thoughts on the question here:

https://github.com/vulkano-rs/vulkano/commit/65254ed10c81694e45555e6044851b718ae200c0

I personally would favor an unified error type that prints the Valid Usage ID (VUID) of the validation error and debug statement.  Panics, while safe, are considered rude by some.

Fits nicely with the try operator.

**Comment by Rua** [comment]
"Rude" maybe, but if you return an error, what's the user going to do with that error?

**Comment by gurchetansingh** [comment]
I'm trying to use Vulkano for virtualization.  The guest may be assumed to be evil, and send untrusted input to Vulkano.

For virtual machines, it's preferably to return an error in that instance rather than (safely) take down the process.  See comments here:

https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/2626487/4..7/rutabaga_gfx/src/rutabaga_gralloc/vulkano_gralloc.rs#b96

I guess it backs to the question: "Is Vulkano a validation layer?".  I think tomaka's original vision is yes, it should be a Rust-based validation layer.  A Rust based validation layer would of course be better than a C++ layer.  

But Vulkano doesn't have a 1:1 mapping of Vulkan apis.  It's possible, but would take many refactorings.  And LunarG's validation layer is quite good.  If your Ash change goes well, it may be worth trying to convince LunarG to leave their mud huts and embrace Rust 🙂.

Maybe in the long run, we can organize the validation such a way the user can be disable via feature flag for performance.

cargo build --features=super-unsafe-disable-validation

**Comment by Rua** [comment]
You're using `UnsafeImage` here, which isn't really guaranteed to validate anything! Only safe types in Vulkano normally validate.

I also see that you propagate the error that Vulkano returns. Where do you actually respond to this error?

**Comment by gurchetansingh** [comment]
For the error, it's printed to a log file eventually, instead of taking down the virtual machine.  

I'm not a huge fan of the ImmutableImage or ImmutableBuffer APIs, since they are quite limiting.  I would just do full-featured, safe Image and Buffer APIs.  That requires a ton of refactoring and the Ash-change as-well tho.  

For my limited use case and `UnsafeImage` implementation, I do believe I am using the UnsafeImage API in a safe way.  It would be terrific to use Vulkano for more expansive use cases as well, but that requires more developers/bigger community than currently exists.  

I do think Vulkano, by the virtue of the Rust language, has a higher ceiling as a validation layer than anything written in C++. This why I prefer `Error` on `panic!` where possible, since errors show the true excellence of Rust.

I would say Error handling/validation in Vulkano is kind of disorganized and haphazard.  LunarG's layer is better, simply since they have full-time employees to work on it.

**Comment by Rua** [comment]
Do you know if [`std::panic::catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) would suit your purposes if validation errors were to be removed?

**Comment by gurchetansingh** [comment]
From an API perspective, I do think Vulkano returning an error using the try operator is better than `std::panic::catch_unwind`.  Simpler for the Vulkano user, I think.

I'm a huge fan of a unified error type (say `VulkanoResult<T>` and `VulkanoError`).  It could wrap a `ValidationError(ValidUsageID)`, and which can just go over the VK spec.

**Comment by faulesocke** [comment]
I currently don't have much time to elaborate on this, but I believe the Rust way of doing this is how it's currently done. Mostly. There are some places where error handling must be re-thought because it assumes that the user `unwrap`s anyways and leaves objects in error states. However, in most places I believe things are fine the way they are.

Panics should only happen when something happens that should not have happened and is completely unexpected. Wrong usage by the user is definitely not a case where a panic should normally occour. Of course every rule has it's exceptions.

I would also vote against a unified error type as it usually makes actual **error handling** much harder while simplifying *error reporting*. This is at least my experience.

**Comment by gurchetansingh** [comment]
Although the Vulkan spec defines errors (`VK_ERROR_DEVICE_LOST`, `VK_ERROR_TOO_MANY_OBJECTS`), these are
dwarfed in comparison to the massive amount of Valid Usage ID (VUID)-based validation errors. 

This goes to the main critique of Vulkano by WebGPU developers: Vulkan is not supposed to be a validated API.  The developer is supposed to run the application via a validation layer when debugging.  When in production, the user is not expected to handle validation errors gracefully.

Vulkano kind of mixes the two, adds it's own errors, and the result is weird and jumbled.

In addition, Vulkan objects and Vulkano objects (such as `StdMemoryPool`) are mixed around.  Vulkan tries to be both a validation layer and middleware.

From a code organization persepctive, I would take these two premises:

     - Yes, Vulkano is a validation layer and we aim to convince LunarG about the power of Rust.
       Rust validation >> C++ validation.
     - Yes, Vulkano does offer middleware capabilities for users.

The logical outcome of these permises is three crates:

    - ash_bindings to replace vk_sys
    - vulkano_core that aims to out-do C++ validation layers with a 1:1 mapping of API functions
      to Vulkan.
    - vulkano_middleware that provides convenience structs such as `StdMemoryPool`

The error types will naturally flow from such a MASSIVE reorganization. The great thing is the user can even turn off validation, and use Rust-like objects over Ash.

These are just my thoughts about Vulkano direction.  The Ash change is absolutely pivotal, and Rua should be made maintainer just for attempting it, and IMO we need LunarG buy-in.

**Comment by Rua** [comment]
@Eliah-Lakhin What do you think of this? I'm still not really convinced that there is much utility in actually returning errors for the caller to handle.

**Comment by Eliah-Lakhin** [comment]
@Rua I would vote to keep `Result<.., Error>` interface :) It's up to user to choose whether they want to recover or unwrap in this case. For example, in my project in most cases I use recovering. Someone maybe not, and in this case writing `.unwrap` everytime might be a bit annoying, but I'm this is a cost user pays for adopting of bad practice.

Anyway, as a compromise solution we can make a feature flag in Vulkano that would turn off recoverable interface for all public API methods, but there will be a lot of work to do this.

**Comment by Eliah-Lakhin** [comment]
> I would also vote against a unified error type as it usually makes actual error handling much harder while simplifying error reporting. This is at least my experience.

@faulesocke Yes, I think so too.

**Comment by Rua** [comment]
Ok, I won't pursue this any further then, but I can leave it open in case people have new input.

**Comment by gurchetansingh** [comment]
My dream of convincing LunarG to adopt Rust is very far-off and impractical (which would be helped by an unified `ValidationError`), and requires the Ash change anyways.

Keeping the way things are sgtm, but we should consider the long-term structure and vision of the project in mind as refactorings continue.

**Comment by Rua** [comment]
How about keeping the individual errors as they are, but grouping all errors that a function can return under an enum like this?

```Rust
enum VulkanoError<R, V> {
    Runtime(R),
    Validation(V),
}
```

This is parameterised, so a function would specify concrete types for R and V in its signature. Then users are still free to respond to any error they wish, but they can also easily filter out validation errors. The enum could also be given methods to make it easier for the user to panic on validation errors (the behaviour I'd like in my project), but I'm not sure yet what the best design for that would be. Ideas welcome.

**Comment by gurchetansingh** [comment]
Yeah, that looks very good.

**Comment by Rua** [comment]
Also, I think including the specific Vulkan VUID in all validation errors in some form is a must too.
