### ISSUE TITLE
shader! will no longer generate descriptor information for variables only used in unreachable code.

### ISSUE THREAD

**Issue by pac85** [vulkano-rs/vulkano#1556]
The changelog says
Breaking shader! will no longer generate descriptor information for variables that are declared but not used in a shader.
But that also happens if they are used in unreachable code. This is very annoying because I often put return at the beginning of a shader for debugging purposes and this fact makes it so this becomes pretty much impossible since nothing will compile.

**Comment by Rua** [comment]
That is kind of an annoying feature, I have to agree. If they are in the emitted SPIR-V code, then I think Vulkano should be able to use them.

**Comment by faulesocke** [comment]
This is definitely annoying. I propose reverting this change or at least making it optional in the next release.

In addition it looks like when I use `add_empty` to skip such removed descriptors, I get panics because the `<UnsafeDescriptorSetLayout as DescriptorSetLayout>::descriptor` method seems to return `None` in this case. According to the docs this method should only return `None` when the descriptor is out of range, i.e. `binding >= num_bindings()`. The code for the auto command buffer also assumes this (here https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/auto.rs#L2433) and therefore panics.

**Comment by Eliah-Lakhin** [comment]
I agree this is annoying.

For reference, it was introduced in https://github.com/vulkano-rs/vulkano/pull/1497 implemented by @Arc-blroth . The main purpose of that PR was fixing description information for shaders with multiple entrypoints. This feature is vital when working with SPIR-V code from the 3rd party source(i.e. RustGPU), and I would like to persist it, but descriptors filtering is probably not needed.

@Arc-blroth, @pac85, @Rua, @faulesocke Can any of you take an action and fix it in proper way?

**Comment by Arc-blroth** [comment]
The major problem with finding all avaliable descriptors is that in a shader with multiple entrypoints, the code might find descriptors for a different entrypoint (which can conflict!). However, it's (AFAIK) impossible to have vulkano find resources that don't get used in SPIR-V 1.0-1.3, because SPIR-V doesn't include enough information to recover those. (SPIR-V 1.4 and up should store enough information to recover unused variables, but I haven't tested this).

> at least making it optional in the next release

I agree with this! Vulkano-shaders can add an extra `exact_entrypoint_interface` flag that'll instruct it to aggressively filter out uneeded descriptors for Rust-GPU consumers, and it'll just be off by default for people who just want a simple shader implemented in GLSL.

**Comment by Rua** [comment]
Hmm, but doesn't Vulkano check whether all the descriptors are properly bound before executing a draw/dispatch call? How does it do that when it can't figure out which descriptors need to be bound?

**Comment by Eliah-Lakhin** [comment]
> Vulkano-shaders can add an extra exact_entrypoint_interface flag that'll instruct it to aggressively filter out uneeded descriptors for Rust-GPU consumers, and it'll just be off by default for people who just want a simple shader implemented in GLSL.

@Arc-blroth Sounds good. Would you mind implementing it, please?

**Comment by Eliah-Lakhin** [comment]
@pac85, @Rua, @faulesocke This issue now resolved thanks to @Arc-blroth . Vulkan-shader is now generating complete description information by default. The fix is on `master` and will be included in the nearest release.
