### ISSUE TITLE
Make shader data generation available at runtime

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1558]
Vulkano-shaders does two things: it compiles the shader (if you're not using `bytes`) and it generates a bunch of data structures and types from the shader. Since the second step is applied to finished SPIR-V code, some of it could in theory be done for shaders that are loaded at runtime. Of course it is still unsafe to actually _load_ these shaders, but there's no good reason to deny users the convenience of having things like pipeline layouts generated for them.

Therefore I propose to add some way to call on Vulkano-shaders to generate shader information at runtime. The `shader!` macro currently defines new types and implements traits on them, which is not possible at runtime: the runtime function has to return a single known type that can represent any pipeline layout, descriptor layout, etc. This would make it similar to the change made to `RenderPassDesc` that was merged recently. However, in this case we have the option to keep `shader!` working as it does now, or also generate a runtime type like the proposed system here.

**Comment by Eliah-Lakhin** [comment]
I believe that moving to runtime shaders wouldn't be a step in right direction regarding Vulkano and GPU usage in general.

Not only because we are loosing a possibility to enforce the user to use shader's structure properly through the static system of types in compile-time and with zero runtime cost too, but because GPUs in general were not designed for shaders extensive reloading. We are loosing GPU efficiency when the user designed end system this way.

So, normally all shaders should be represent by a finite set, and be prepared beforehand, and ideally all loaded in loading time and never change. That's why Vulkano proposing compile-time `shader!` macro as a primary way to design and load shaders. Also, for the shader's generalization and specialization in run time there is a mechanism of Specialization Constants provided by Vulkan and supported in Vulkano too. All GPU vendors recommended this way of the shaders runtime varying as a main and normal method to use(see [Pipeline Dos and Don'ts Section](https://developer.nvidia.com/blog/vulkan-dos-donts/) for example).

In my opinion, what could really improve user experience in Vulkano is implementing a way to share generated types between several invocations of the `shader!` macro.

**Comment by Rua** [comment]
I'm not proposing to abandon `shader!` in any way. It will work exactly the same as before, and provide the same guarantees. I'm proposing to expose some of its features to users who want to do runtime shader loading. Runtime shader loading is and will remain unsafe, but that is a choice the user makes. Exposing some of the macro's functionality for runtime use would at least lessen the unsafety for users wanting to do this (since they can't make mistakes writing their own pipeline layouts, etc), so I'd call that a win.

**Comment by Eliah-Lakhin** [comment]
ok, I don't mind to improve runtime shaders API, so let's make a prototype and see how it works :+1:
