### ISSUE TITLE
Feature request for vertex attribute divisors (used mainly in reducing buffer bandwidth when working with highly instancible vertex data)

### ISSUE THREAD

**Issue by Nhlest** [vulkano-rs/vulkano#1582]
Are there any plans to add support for [Instancing divisors](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_vertex_attribute_divisor.html)
So far the only rust vulkan library that provides any support for this vulkan feature is ash (from what i can tell), but it would be extremely nice to have it in a more high level binding library like vulkano :)

**Comment by Rua** [comment]
I think it's doable, but I have to look into how Vulkano should support features from extensions.

**Comment by Rua** [comment]
I haven't forgotten about this request! With Vulkano 0.24, feature and extension support is much improved, so I've been taking a look at this again. It looks like, in order to integrate support for this into Vulkano, something needs to happen with the `VertexDefinition` trait. That's something I've been wanting tackle for a while already, so this makes a good opportunity for it I suppose.
