### ISSUE TITLE
Any way to avoid merge conflicts in the changelog?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1590]
As I'm sure @Eliah-Lakhin and others have noticed, most merge conflicts happen in the `CHANGELOG_VULKANO.md` file. This presumably happens because every PR modifies it, and all the changes are concentrated in the same area of the file. It would be nice if not every PR had merge conflicts, that need to be fixed, only to reappear as soon as another PR is merged before it.

I don't know much about Github's features, but I believe it may have something to handle changelogs for Vulkano? Or perhaps there's a way to handle the current file so that there's no conflicts. Any ideas?

**Comment by Eliah-Lakhin** [comment]
@Rua Yes, I completely agree. The changelog is something that is the most annoying factor involved in review process. I don't know how to properly enforce changelog conflicts autoresolving, but I think I can change the Pull Request template requirements to ask people to put incoming changelog changes into the PR description itself, instead of the actual changes in the changelog. Then, after the PR merge, I will transfer each entry myself manually.

**Comment by Rua** [comment]
I was thinking of that as well. As long as you are up to editing the changelog yourself, I think that's workable.

**Comment by Eliah-Lakhin** [comment]
@Rua ok, I will change the requirements starting from the next week.

**Comment by Eliah-Lakhin** [comment]
Done.
