### ISSUE TITLE
Ideas on setting attribute format of vertex shader inputs

### ISSUE THREAD

**Issue by JennToo** [vulkano-rs/vulkano#1667]
*   Version of vulkano: 0.25.0
*   OS: Linux (Ubuntu 20.04)
*   GPU (the selected PhysicalDevice): Intel(R) HD Graphics 4600 (HSW GT2) (type: IntegratedGpu)
*   GPU Driver: mesa-intel
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue:
https://github.com/Nitori-/vulkano/commit/3d12692bc7b2cf205ba63c5e750d36d2a1d24c92

# Issue
If you try to run the modified triangle example I linked above, you'll get an error like this:

`IncompatibleVertexDefinition(FormatMismatch { attribute: "color", shader: (R32G32B32Sfloat, 1), definition: (U8, 3) })'`

On its surface this isn't entirely unexpected. The shader looks like it wants a 3-float input format (`R32G32B32Sfloat`), but we're giving it integers.

However, what I really want to use is a normalized format like `R8G8B8Unorm`. As far as I know, there's not a way for me to indicate this in the GLSL shader source itself. To me it seems like the `shader!` macro needs a way to provide hints about what formats you actually want to use. I think it would still be possible for it to validate that you've chosen a compatible format (e.g. if I hinted that I wanted `R8G8B8Unorm` but the shader input was a `vec4` that could and should give an error).

Assuming that `shader!` would be the right place to fix this,I briefly peeked at the `shader!` source. But before I got too far on any kind of implementation I thought it would be good to see what people think about this problem. I'm thinking maybe roughly a syntax like this (but I'm far from an expert on macro ergonomics):

```rust
    mod vs {
        vulkano_shaders::shader! {
            ty: "vertex",
            src: "
                   #version 450

                   layout(location = 0) in vec2 position;
                   layout(location = 1) in vec3 color;

                   layout(location = 0) out vec3 v_color;

                   void main() {
                       gl_Position = vec4(position, 0.0, 1.0);
                       v_color = color;
                   }",
            format: {
                color: Format::R8G8B8Unorm
            }
        }
    }
```

**Comment by Rua** [comment]
I think the problem lies in `VertexMemberTy::matches`. It doesn't seem to take into account that normalised integers in the vertex buffer can be converted into floats in the shader. The table at https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap43.html#_identification_of_formats should probably be taken into account.

**Comment by Nitori-** [comment]
Ah yeah I think that approach could work. I think we'd need to update a little more than just the `VertexMemberTy::matches` function, since we'd also need to translate the inferred format (from `R32G32B32Sfloat` to `R8G8B8Unorm` in this example) when we actually bind the value to the [`VkVertexInputAttributeDescription`][1]. I haven't traced through where that lives in vulkano quite yet, but it seems possible.

I like that approach more than format hints in the macro, since it keeps everything implicit still (and thus less prone to error).

There are some edge cases that this would miss (e.g. what if I want to flip from RGB to BGR in my attributes), but that is at least outside my own current usecase.

[1]: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkVertexInputAttributeDescription.html

**Comment by Rua** [comment]
The part of the `shader!` macro that generates the format from the shader code is here: https://github.com/vulkano-rs/vulkano/blob/master/vulkano-shaders/src/spirv_search.rs#L18. However, I'm not sure if that's really the right approach; a "format" is a Vulkan data format thing, and doesn't really apply to shader inputs. As far as the shader is concerned, it's defined as "vector of 3 32-bit floats" (in GLSL, `vec3`), so something like that is really what the macro should be generating.

The format specification only comes in when you have a Vulkan data buffer or image, and want to describe how its data is laid out and how it should be interpreted. But once this data is being fed into the shader, there is a conversion step between the data format and the shader input. So Vulkan's `R32G32B32Sfloat`, `R8G8B8Unorm` or `B8G8R8Unorm` all get converted to `vec3` via a process internal to Vulkan.

What the `matches` function should be doing is checking whether the Vulkan driver is actually capable of this conversion for a given Vulkan format and shader input type. In other words, whether the data in the vertex buffer can be converted to what the shader wants. For this, of course, there's rules defined in the Vulkan spec: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap22.html#fxvertex. Different drivers are capable of different conversions, so the capabilities of the current driver should be queried via Vulkano's `Format::properties` method before constructing a graphics pipeline.
