### ISSUE TITLE
Release & Development

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1698]
@Eliah-Lakhin @Rua, just some thoughts on how we could improve vulkano accessibility.

1. Make an `dev` branch for all active changes to go into, keeping `master` as the current released version.
    - Currently we do tags (at least most of the time when we remember)
    - This would remove the need of the https://github.com/vulkano-rs/vulkano-examples repo.
        - This repo hasn't been maintained.
        - It should be updated with every release with the release's examples.
    - For users looking for examples for vulkano, navigating to the main repo will yield them with the current releases examples without additional navigation.
        - We could also just add some info to the README pointing users to the tag releases to view the examples they are after, but I feel like some users may not read that.
2. More effort should be put into maintaining the `vulkano.rs` website.
    - Most users will land here first when they are looking for examples. This will cause them to use code that is out of date and then run into errors.
    - The website has more space for describing how things works than plain comments.
    - If the website were more up to date we could reduce the amount of examples in the main repo.
         - We could remove examples that are only a few line changes different than basic examples and create a section on the website dedicated to that feature and be able to describe how the feature works better.

**Comment by Eliah-Lakhin** [comment]
@AustinJ235 

1. Keeping `master` as a current released versions branch exclusively has two drawbacks:
     - If the `master` branch is Github default that would confuse contributors when they open new PRs as PRs go to Github default branch by default. If the releases branch would not be Github default that would be almost similar to just maintaining release tags as we do now.
     - If we dedicate `master` for releases exclusively, prior commit history in that branch would confuse the users. So "releases" branch normally should be started as a bare new branch.

   All in all I don't mind about dedicated releases branch, I just don't think it would be much differ from release tags for the end users, and it would increase maintainability for maintainers.
2. As of Vulkano examples repo. I totally agree. We should remove Vulkano-examples. I, honestly speaking, don't understand why do we need it at all :) It only confuses new users. All relevant and up to date examples are in the main repo(here).
3. And I also agree that we should put more efforts to Vulkano.rs website. The technical problem is we just don't have access to website(only to its repo). Website hosting is in @tomaka's hands.

   I would migrate the website to Gitthub pages to the main Vulkano repo, and reconfigure DNS hosting to use Github pages instead. We will need to ask Pierre's help with configurations, but we can start with the content migration beforehand.

   > If the website were more up to date we could reduce the amount of examples in the main repo

   However, I would keep current examples in the repo too. Not because of accessibility, but because they also serve as a sort of functional tests.

**Comment by Rua** [comment]
I agree with Eliah on the first point. `master` should be used for the current development version, as that's what people expect and what everyone does anyway. I don't know if a branch for releases is useful; what would it add over tags?

**Comment by Rua** [comment]
I don't think anything else is going to be discussed here, so I'll close it.
