### ISSUE TITLE
Image Clear Rect

### ISSUE THREAD

**Issue by Amjad50** [vulkano-rs/vulkano#1749]
Hello,

I would like to be able to clear rect of an image, currently we can't. I'm not sure if vulkan itself support this, I found command `vkCmdClearAttachments`, which seem to be commented code for it in:

https://github.com/vulkano-rs/vulkano/blob/eb7e0c9ce06f52cd1877e5274a93216bd910475f/vulkano/src/command_buffer/sys.rs#L689-L710

Will this function enable us to clear rect? Or is there any other way to achieve that.

Thanks

**Comment by Rua** [comment]
I wonder why this function was commented out. Perhaps it didn't work correctly or was unsafe to use?

**Comment by Eliah-Lakhin** [comment]
@Amjad50 Well, due to a git blame it was commented out by Tomaka a while ago. I can't say for sure why it was removed. Perhaps, it was under-implemented, so maybe this is just a prototype of incomplete function. Following the commented, maybe Tomaka didn't decide about parameter's types and the way they could be lesser uplifted in safe way. 

If you think it could be finished(preferably in safe way) I will be glad to include the PR in the mainstream codebase.

**Comment by Amjad50** [comment]
@Eliah-Lakhin I'll try to look into it, from what I can see there doesn't seem to be any already defined structures for the types that we will need in this function (like ClearAttachements). But I can look into it and publish a PR if I found a good solution
