### ISSUE TITLE
When exactly are pipeline barriers inserted?

### ISSUE THREAD

**Issue by danielkeller** [vulkano-rs/vulkano#1798]
I'm trying to understand how vulkano's automatic synchronization works. My understanding so far is that `PrimaryCommandBuffer::execute_after` looks at the memory accesses that happen in the command buffer, and the ones in the future, and adds pipeline barriers appropriately. But what about `sync::now()` and `GpuFuture::join()`? If I read some memory in one command buffer and write it in another, execute them both after `now()`, then `join()` them, does the read see the write? What If I call `flush()` on one or both of them before joining?

**Comment by Rua** [comment]
Pipeline barriers are inserted during recording, so once the command buffers are built, no barriers can be inserted anymore. That means that barriers can never be inserted between command buffers, only within one. And since, during recording, one command buffer doesn't know which other command buffers exist or which it will be executing in tandem with, another mechanism is needed here.

The way Vulkano currently works is like this. When a command buffer is submitted for execution, all resources inside of it are "locked", according to the type of access the command buffer performs (shared or exclusive). If a resource is found to already have a conflicting lock (it's already submitted via another command buffer, and at least one of them needs exclusive access), then the submission is aborted and you get an error. This is what you'd get if you simply execute two command buffers after each other, or in entirely unconnected `GpuFuture`s. The way to prevent this error is to signal a semaphore between the two command buffers, which makes the second command buffer wait for the first.

This approach is not ideal; it has some flaws and speed penalties, and perhaps bugs too. A semaphore is quite heavy-handed as a synchronisation primitive because it stalls the entire queue. A pipeline barrier is lighter and more specific in which parts of the pipeline it affects.

In principle, a pipeline barrier could be inserted between two command buffers on the same queue, because the "scope" of a barrier is the queue as a whole (or a single subpass), it's not restricted by the command buffer boundaries. It's possible to record a new command buffer with only the barrier, and insert it between the two command buffers when submitting. If this were implemented, then a lot of the locking would become unnecessary; only resources that were created for sharing across queues would need semaphores and locking for synchronisation, single-queue resources could make do with pipeline barriers alone.

**Comment by danielkeller** [comment]
Thanks! So are the resources used in a command buffer unlocked once you call `then_signal_semaphore`? I looked in the code and I could only find them being unlocked when you wait for a fence. Also, [the docs](https://docs.rs/vulkano/0.27.1/vulkano/sync/index.html#executing-an-operation-after-a-future) appear to say that `then_execute` is enough to synchronize two command buffers on the same queue, is that out of date?

**Comment by Rua** [comment]
They are unlocked once the CPU side of things can be certain that the submission is done executing, which is when you wait for a fence. A semaphore "hides" all the submissions before it, so that they no longer conflict with the submissions after it. I don't know if `then_execute` works the way you described, but I suppose you can test it by making two command buffers that write to the same resource, and seeing if an error happens.

**Comment by Rua** [comment]
I think this is answered now? I'll reopen if there are more questions.
