### ISSUE TITLE
Triangle example panics when minimizing the window

### ISSUE THREAD

**Issue by jedel1043** [vulkano-rs/vulkano#1892]
# Issue

Running the triangle example and minimizing the window makes the program crash with the message:

```bash
thread 'main' panicked at 'assertion failed: image_extent[0] != 0 || image_extent[1] != 0'
```

The stacktrace points to the `Swapchain::validate` method as the culprit:

https://github.com/vulkano-rs/vulkano/blob/5c6bbe0be4f2890b474d551b89fc2b23fb31fbaa/vulkano/src/swapchain/swapchain.rs#L394-L396

# System Info

*   Version of vulkano: 0.29.0 and https://github.com/vulkano-rs/vulkano/commit/5c6bbe0be4f2890b474d551b89fc2b23fb31fbaa
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): NVIDIA GeForce GTX 1050
*   GPU Driver: Nvidia driver 511.65
*   Vulkan Runtime: 1.0.33.0
*   Vulkan SDK: 1.3.211.0
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs

**Comment by ryco117** [comment]
@jedel1043 I can reaffirm that this is the behavior when minimizing on Windows, which coincidentally is why my new example from yesterday contains the check
```
let dimensions = surface.window().inner_size();
if dimensions.width == 0 && dimensions.height == 0 {
    return; // On Windows, minimizing sets surface to 0x0. Do not draw frame.
}
```

I'd be willing to shotgun this into the other examples so they don't crash on minimize.

@Rua @AustinJ235 I'm also curious if it makes sense to change the above assert into returning `SwapchainCreationError::ImageExtentNotSupported` since there is a plausible runtime condition for someone to pass a zero by zero dimensions. I will concede that it is still the callers responsibility to not attempt to create a zero by zero swapchain.

**Comment by AustinJ235** [comment]
It might be more ergonomic to return an error in this case. Basalt has had this check in place for a while now, but from a new user perspective it might be confusing why their program panics.

**Comment by Rua** [comment]
I think turning this into a proper error makes sense, and adding it to the other examples. Do you want to make a PR for it?

**Comment by ryco117** [comment]
@AustinJ235 @Rua Thanks for the quick responses.

Curious. The assert statement references [VUID-VkSwapchainCreateInfoKHR-imageExtent-01689](https://khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSwapchainCreateInfoKHR.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01689), but the language of "width and height **must** both be non-zero" (emphasis theirs) suggests that neither dimension can be zero, whereas the code asserts at least one non-zero dim. Whoops.

Will make the appropriate validation and code-sample changes. Cheers
