### ISSUE TITLE
Please advice how to make timestamp queries working

### ISSUE THREAD

**Issue by jczaja** [vulkano-rs/vulkano#2195]
# Spec

*   Version of vulkano: 0.33.0
*   OS: Fedora Linux 36
*   GPU : Intel Tigerlake (Gen12)
*   GPU Driver: Vulkan Instance Version: 1.3.204

# Issue

Hi, I'm new to vulkano&vulkan. After making some basic examples I wanted to check GPU execution time. So I tried to use timestamp queries, but I got an error : _Permission denied_ triggerred from here:
https://github.com/vulkano-rs/vulkano/blob/bb7990fd491bed13746c8b85408097b5f0799c50/vulkano/src/command_buffer/commands/query.rs#L147

Please advice how to to make timestamp queries working or suggest other way of measuring time og GPU kernel execution.

Thanks very much for working on this fantastic project!

**Comment by jczaja** [comment]
Thanks for suggesstion @Rua. 

I still have a problem using timestamp queries as in my situation there is no values written as timestamp queries results e.g. I get nothing.

I try to use timestamp queries to measure execution time of my compute shader and timestamps are written in GPU buffer (copy_query_pool_results() ) as here: 
https://github.com/jczaja/test-rust-vulcano/blob/0cb3cb51d401c19baebee9a2d8f4da69d40622b3/src/main.rs#L191-L214

and then I get those results by reading this buffer:
https://github.com/jczaja/test-rust-vulcano/blob/0cb3cb51d401c19baebee9a2d8f4da69d40622b3/src/main.rs#L225-L237

but inital values (zeros) are printed. 

Full example is [here](https://github.com/jczaja/test-rust-vulcano)

Please advice how to proceed

**Comment by jczaja** [comment]
Ok, I narrowed down the problem. All works fine if my compute shader is not exceeding 20 s . What I mean is that above 19s compute shaders works fine, but if only I try to use timestamp queries then I got all sort of problems "DeviceLost", "ExclusiveAlreadyInUse" etc. My GPU in Integrated graphics (Tigerlake).

**Comment by HadrienG2** [comment]
This is probably the OS killing your shader (and other bits of your Vulkan context along the way) because it thinks you've been hogging the GPU for too long.

As you likely have already noticed, GPUs have very limited preemptive scheduling capabilities, and it is very easy to freeze rendering while the GPU is waiting for a long-running shader to terminate. Since indefinitely freezing rendering of the entire desktop of a modern GUI operating system is not considered acceptable behavior from applications, several OSes have implemented measures to kill long-running shaders, restoring normal desktop functionality.

I think the time limit is tunable on Windows, you may want to google it up if that's the OS you are using.

**Comment by jczaja** [comment]
ok. thanks for explanation
