### ISSUE TITLE
White background on the first frame [Windows]

### ISSUE THREAD

**Issue by ekzee** [vulkano-rs/vulkano#2263]
*   Version of vulkano: 0.33.0
*   OS: Windows
*   GPU (the selected PhysicalDevice): NVIDIA GeForce RTX 2080 SUPER
*   Can reproduce in [triangle_v1.3](https://github.com/vulkano-rs/vulkano/blob/0.33.X/examples/src/bin/triangle-v1_3.rs)

# Issue

Hello, there is a minor issue which were bothering me for quite a while. On Windows, when I start my app, background of the first frame is white, then it changes to clearColor. I have the very default winit EventLoop setup (and the issue is reproducible in triangle example). According to [this issue](https://github.com/rust-windowing/winit/issues/1290) it seems that this happens on windows when it didn't receive anything to draw, but Im quite puzzled where else should I put my render call besides Event::RedrawEventsCleared to fix that.

**Comment by Rua** [comment]
This happens because the window is visible before anything draws to the window. The window isn't filled with contents until you present the swapchain image for the first time. Before that, it's anyone's guess what it contains. It may be possible to hide the window until after the swapchain has been presented, but that may also mess with the swapchain in other ways. I think the best option is to just accept this as normal Windows behaviour.

**Comment by ekzee** [comment]
I just tried setting window invisible in the WindowBuilder and then calling window.set_visible(true); after presenting swapchaing. Everything works just fine and annoying white flash is gone, thank you =)
But I will keep in mind your note about this possibly messing with the swapchain.
