### ISSUE TITLE
vulkano-shaders generates wrong padding for vec3 array[2]

### ISSUE THREAD

**Issue by svenstaro** [vulkano-rs/vulkano#298]
So I have this:

```
struct MyStruct {
  vec3 this_breaks[2];
  uint something;
};
```

Which generates this excerpt:

```
    pub this_breaks: [[f32; 3]; 2] /* offset: 0 */,
    pub _dummy0: [u8; 8],
    pub something: u32 /* offset: 32 */,
```

Now the offset is obviously wrong. It should look like this:

```
    pub this_breaks: [[f32; 3 (and then we need a +1 padding here somehow)]; 2] /* offset: 0 */,
    pub something: u32 /* offset: 32 */,
```

This had led to some actual problems in my code. If use use a `vec4 array[2]` this works totally fine, by the way.

**Comment by thiolliere** [comment]
I also have this issue with a mat3

**Comment by singron** [comment]
It looks like the struct generator ignores ArrayStride and uses the default rust array layouts, which are wrong for vec3[x], mat3[x], and arrays of various non-square matrices as well.

I think it may also be ignoring MatrixStride as well. mat2, mat3, and mat4 all have a MatrixStride of 16 with glslangValidator, so it seems like this should mess with pretty much any matrix that doesn't have columns of length 4 even if they aren't in an array. I haven't confirmed that issue though so I might have just overlooked something.

Any ideas for fixing this? I don't think it's possible to tell the rust compiler to use an arbitrary array stride without wrapping each element of the array with a struct that has dummy padding. However, this makes the generated code difficult to use since there might be these wrapping structs all over the place depending on if rust and spirv agree on the array stride. I have a patch that just rejects these shader programs and requires the programmer to insert wrapping structs in the GLSL code. It's more work for the programmer, but then the GLSL code has the same structure as the rust code.

**Comment by rukai** [comment]
Compile time error handling for this case implemented by https://github.com/vulkano-rs/vulkano/pull/1050
