### ISSUE TITLE
Recreating swapchain may cause segfault

### ISSUE THREAD

**Issue by porky11** [vulkano-rs/vulkano#382]
when I call `swapchain.recreate_with_dimension([x,y]).unwrap();` without reassigning it to my swapchain variable, and then try to reuse the swapchain, my program gets a segfault when calling `swapchain.present(&queue, image_num).unwrap();`
I think, when recreating the swapchain, the variable `swapchain` should either be moved or recreated without having to reassign it.

**Comment by tomaka** [comment]
Thanks for the report.

In theory it should be possible to continue using the old swapchain, there I think it's best to leave the choice to the user. Maybe adding a `#[must_use]` attribute to the swapchain is the best solution.

I don't know why you have a segfault. Maybe it's the driver's fault, maybe it's vulkano's fault. Since I'm not confident enough in vulkano's robustness I can't tell.
