### ISSUE TITLE
Creating an uninitialized CPU-accessible buffer or image should be unsafe

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#67]
Asking on IRC, it seems that uninitialized memory really is unsafe. It is an undefined behavior to read from it, and the only reason why things work today is that the compiler doesn't realize it's uninitialized.

**Comment by lfairy** [comment]
It looks like the methods in question are already deprecated (e.g. [ImmutableImage::new](https://docs.rs/vulkano/0.9.0/vulkano/image/immutable/struct.ImmutableImage.html#method.new)).

Am I correct to say this can be closed after we remove those deprecated methods?

**Comment by Rua** [comment]
Since the memory is allocated by Vulkan before it's exposed to Rust, from the perspective of the Rust compiler it's the same as if the Vulkan implementation had written random bytes to the memory before handing it over to Rust. I don't think they could be considered "uninitialised" in the compiler UB sense.
