### ISSUE TITLE
Uniform question

### ISSUE THREAD

**Issue by portaloffreedom** [vulkano-rs/vulkano#795]
First, I'm not very expert in vulkan, still learning. Done with the premises:
I'm trying to write a simple game engine with this library underneath. I have a problem with uniforms. I understand there are two methods of uploading them to the GPU.
First one is to use `CpuBufferPool`, second one is to use `CpuAccessibleBuffer`

The first one seems faster on the description. But it requires to recreate the command buffer pool every frame and it seems kind of redundant for me.
Second one allows me to cache the command buffer in between frames and that's nice. But I see that the `CpuAccessibleBuffer` is using a fence to operate, slowing things down considerably.

What I had in mind is to create a Uniform buffer for every framebuffer at startup and at runtime upload the new uniform asynchronously and let the draw command start right after the upload finished. What is the best strategy to achieve this result? Possibly by caching the command buffers.

Thanks

**Comment by tomaka** [comment]
You should not be worried about recreating command buffers at every frame. That's how things were designed in Vulkan. There are some situations where you can reuse command buffers between frames, but they are rare.

**Comment by arianvp** [comment]
Another question about this.   If I want to use `CpuBufferPool` to upload `Uniforms` every frame, for example, to upload my  world matrix every tick,    I have to create a new `PersistentDescriptorSet` every tick, like in https://github.com/vulkano-rs/vulkano/blob/ddb66a5513033fdeb9d8caf0b05187b812045dae/examples/src/bin/teapot.rs#L195


However, the documentation of `PersistentDescriptorSet` mentions that you should _not_ create them in performance-critical paths, and that they should be long-lived. This seems to go exactly against the way it should work.

My other idea is to just create the Set once, and modify a `CPUAccessibleBuffer` at each end of a frame, so that at the next frame, the shaders picks up the new uniform, but this requires `wait()`ing for the GPU Future, which is wasteful. I would prefer to do this as asynchronous as possible, which is why I'm interested in the `CpuBufferPool`.

https://docs.rs/vulkano/0.7.2/vulkano/descriptor/descriptor_set/struct.PersistentDescriptorSet.html

> Creating a persistent descriptor set allocates from a pool, and can't be modified once created. You are therefore encouraged to create them at initialization and not the during performance-critical paths.


Should I be worried of creating a new `DescriptorSet` every frame?

**Comment by arianvp** [comment]
Would this be a viable option? that avoids creating the `descriptorset` each tick?
1. Create and Attach to the DescriptorSet a `DeviceLocalBuffer` for the uniforms.
2. Create a CpuBufferPool
3. In the loop:
   1. Get a subbuffer from the CpuBufferPool
   2. Put the uniforms inside
   3. Create and Submit a `copy_buffer(sub_buffer, local_buffer)` command
   4. join this future with previous iteration
   5. Go back to beginning of loop

**Comment by tomaka** [comment]
@arianvp I encourage you to check out the `FixedSizeDescriptorSetsPool` struct. It is specifically made for when you want to change buffer every frame.

**Comment by arianvp** [comment]
I do not need a different descriptor every frame though. Just different buffer contents.  I can change the underlying buffer without changing the descriptor, right?

**Comment by tomaka** [comment]
Oh didn't see your latest post where you mention copying from a CPU buffer to a device-local buffer. This is a good option, and the best option if you have a reasonable amount of data.
