### ISSUE TITLE
vulkano-win shouldn't take ownership of my window

### ISSUE THREAD

**Issue by swiftcoder** [vulkano-rs/vulkano#920]
For reasons largely tangential to vulkano, I have a desire to hoist the winit::Window into the main function of my application. Unfortunately, vulkano-win likes to both create and assume ownership of the window, even though it seems to have no need of it after constructing the Surface.

Would you be opposed to moving to a model whereby the Surface constructor takes the window by reference, and doesn't store it at all?

**Comment by branan** [comment]
There's no good way to do that, unfortunately. The `Window` must outlive the `Surface` to avoid hitting UB in Vulkan. Due to how Vulkano keeps the surface's `Arc` reffed in various places (through the swapchain, into swapchain images, and then into the various Futures that represent ongoing rendering work), propagating a lifetime for a `&Window` type parameter is hilariously complicated. I looked in to it.

If you're willing to write some unsafe code, you could parameterize `Surface<W>` with `()` or something like that, and handle calling the unsafe functions from the guts of vulkano-win yourself. This is definitely an unsafe operation, since you now have to ensure your Window outlives your Surface.

**Comment by Shookbelf** [comment]
Why not simply let Surface take an Rc to the Window?

**Comment by dwerner** [comment]
I hit a similar issue, however you're not required to use vulkano-win to use vulkano. In my code I just forked vulkano-win's platform specific bindings of `winit_to_surface()` to take an Arc<winit::Window>.

For example:
```
type AMWin = Arc<winit::Window>;

#[cfg(target_os = "windows")]
pub unsafe fn winit_to_surface(instance: Arc<Instance>, win: AMWin)
                           -> Result<Arc<Surface<AMWin>>, SurfaceCreationError> {
    use winit::os::windows::WindowExt;
    let hwnd = win.get_hwnd();
    Surface::from_hwnd(instance,
                       ptr::null() as *const (), // FIXME
                       hwnd,
                       win.clone() )
}
 
```

Then I can capture an `Arc<Surface<AMWin>>` like this:

```
        let surface: Arc<Surface<AMWin>> = unsafe {
           match vulkano_win_patch::winit_to_surface(instance.clone(), window.clone()) {
               Ok(s) => s,
               Err(e) => return Err("unable to create surface..".to_string())
           }
        };

```

In this scenario I can recreate the surface which now merely owns a copy of the `Arc` type instead of owning the `winit::Window` itself.
