### ISSUE TITLE
[Question] How to use renderdoc with vulkano for debugging?

### ISSUE THREAD

**Issue by arianvp** [vulkano-rs/vulkano#924]
If I try to launch one of the examples to inspect with renderdoc I get the following error:

```
thread 'main' panicked at 'No instance with surface extension: ExtensionNotPresent', /checkout/src/libcore/result.rs:916:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Warning - send: 111
```

Just running the executable does work.

Happens both on Wayland and XOrg. FYI

**Comment by tomaka** [comment]
RenderDoc on Windows *just works*, and it's supposed to be the same on Linux.

It's not impossible that there is a problem in RenderDoc.
Maybe let's ping @baldurk just in case they know something about it.

**Comment by ishanjain28** [comment]
@baldurk I am on arch linux. The latest version of renderdoc available on AUR is 1.0.1 released in March. I get the same `ExtensionNotPresent` error when I try to load `VK_LAYER_RENDERDOC_Capture`. 


renderdocmd Output
```
renderdoccmd x64 v1.0 built from NO_GIT_COMMIT_HASH_DEFINED
Packaged for Arch (1.0) - https://aur.archlinux.org/packages/renderdoc
APIs supported at compile-time: Vulkan, GL.
Windowing systems supported at compile-time: xlib, XCB, Vulkan KHR_display.
```

Nvidia Driver version 390.48

All of my code is [here](https://play.rust-lang.org/?gist=7504e12b51e4f94e41de2bb901d08b9f&version=stable)

**Comment by baldurk** [comment]
I don't know rust or vulkano, so maybe I'm missing something, but the code there still doesn't show exactly which extensions you're trying to load (some are implicit from `..vulkano_win::required_extensions()`), and it doesn't seem to enumerate the to see which extensions are actually available - assuming you're on the 1.1.70 vulkan loader, enumerating instance extensions should return the right filtered results. You didn't say if you were testing on wayland or not, presumably on wayland the required extensions list will include an extension that isn't supported.

Also FYI you shouldn't directly activate the renderdoc layer like that, it's not an explicit layer that should be referenced by the application, instead you should run your program through the renderdoc UI or CLI tool to make sure it's initialised properly.

**Comment by baldurk** [comment]
If you're loading `VK_KHR_wayland_surface` then that explains the problem since renderdoc doesn't support wayland. You should enumerate available instance extensions first before trying to create an instance, and if you're using a recent loader then renderdoc can filter unsupported extensions out of the enumerated results. That means you can check to make sure extensions are supported and have a better error message with specifically which extension is not supported, or have a fallback path.

Also on X11 I'm not sure why it's asking for `VK_KHR_wayland_surface`, but I guess that's a vulkano issue.

**Comment by ishanjain28** [comment]
@baldurk You are absolutely correct! The program was crashing when I enabled `VK_LAYER_RENDERDOC_Surface` and `VK_KHR_wayland_surface` at the same time. 

I tried it again but this time I disabled `VK_KHR_wayland_surface` and it works fine. 


The fix for this should be added in `vulkano_win`. It is the module responsible for creation of window and it should not enable extensions that are not required/Would never be used. 

Thanks again.
