### ISSUE TITLE
Triangle demo: Closed vs CloseRequested

### ISSUE THREAD

**Issue by David-OConnor** [vulkano-rs/vulkano#971]
It appears that in the version of Vulkano on Cargo (0.9) uses WindowEvent { event: winit::WindowEvent::Closed, .. }, (Same for old versions on Github) while the version on Github (CAO this date) uses WindowEvent { event: winit::WindowEvent:closeRequested, .. }

This means that if you install Vulkano from Cargo, and try the example code, it won't compile without changing closeRequested to Closed

**Comment by rukai** [comment]
If you want examples that are compatible with the latest published version of vulkano on crates.io then you can retrieve it from the git history either locally or on github. e.g. https://github.com/vulkano-rs/vulkano/blob/5e73ce96a1dab5dcfd12e05d0bb13bed29e717fd/examples/src/bin/triangle.rs

The examples in the latest git master can't be expected to work with the latest published version of vulkano on crates.io, otherwise we wouldnt be able to make breaking changes ever.
