### ISSUE TITLE
How to use vulkan-win = "0.9.0" with winit?

### ISSUE THREAD

**Issue by MadWombat** [vulkano-rs/vulkano#987]
There seems to be a disconnect between master and the published 0.9.0. I tried to compile a minimal windowed program using the same versions that examples use (vulkano-win is marked as 0.9.0 and Cargo.toml for examples lists winit = "0.16.0") and failed with the `no method named `build_vk_surface` found for type `winit::WindowBuilder` in the current scope` error. Which tells me that my winit version is out of sync with the vulkano-win. What version of winit should I use with vulkano-win 0.9.0 from crates.io?

**Comment by thiolliere** [comment]
You should be able to find it in the `Cargo.lock` file.
it is version 0.11

**Comment by DancingBard** [comment]
@MadWombat as `vulkano-win` is just one file (https://github.com/vulkano-rs/vulkano/blob/master/vulkano-win/src/lib.rs) you can just copy that to your project and use even (latest) `winit 0.16` with the latest vulkano version (`0.9.0` at the time of writing this)

I do it, since I read this: https://www.reddit.com/r/rust/comments/8raywa/winit_window_handling_library_now_has_hidpi/e0reico/
